[mode]
connection_mode = 1
auto_replace = y

[Payload]
payload:python3 payload_generator.py '0001{[0,3]}'\x00\x01\x00\x00\x01\x03
GET http://u.airtel.in/1 HTTP/1.1[crlf]Host: u.airtel.in[crlf]Connection: keep-alive[crlf][crlf]
proxyip = 202.56.231.117
proxyport = 8080

[ssh]
host:fmod.com
port = 8080
username = edwin
password = 21042424
enable_compression = y

#authentication method : password | publickey
auth_methode = password

[sni]
server_name =kycagile.airtelkenya.com
sni port:104.18.8.127
injectionmethod:[SSL & v2ray]
portal:portal.ncnd.vodacom.co.tz
